name: Upload to S3

on: push

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY}} AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_KEY}} aws s3 cp . s3://${{secrets.AWS_BUCKET}}/
