name: Upload to S3

on: push

permissions:
  id-token: write # required to use OIDC authentication
  contents: read 
  
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::669840494653:role/rw_ttd-temp_githubactions
          aws-region: us-west-2
          role-session-name: GitHubActions
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 ls

      - uses: Sample-account-github-jira/upload-s3-action@master
        with:
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: '.'
          destination_dir: 'kjv8qkRk-'
          run: aws sts get-caller-identity --profile GitHubActions
